sudo: required
language: go
go:
- 1.7.x
addons:
  apt:
    packages:
    - git
    - make
    - curl

env:
  - DOCKER_IMAGE_NAME=cloudposse/route53-kubernetes

services:
- docker

install:
- make init
- make go:deps-build
- make go:deps-dev
- make docker:login

script:
- make go:deps
- make go:test
- make go:lint
- make go:build
- make docker:build

after_success:
- make travis:docker-tag-and-push
