sudo: required
language: go
go:
- 1.7.x
addons:
  apt:
    packages:
    - git
    - make
    - curl

env:
  - DOCKER_IMAGE_NAME=cloudposse/route53-kubernetes

services:
- docker

install:
- make deps-build
- make deps-dev
- |-
  docker login \
    --email="$DOCKER_HUB_EMAIL" \
    --username="$DOCKER_HUB_USERNAME" \
    --password="$DOCKER_HUB_PASSWORD"

- |-
  curl https://raw.githubusercontent.com/cloudposse/build-harness/master/scripts/travis_docker_tag.sh > travis_docker_tag.sh \
  && chmod +x travis_docker_tag.sh

script:
- make deps
- make test
- make lint
- make build
- docker build -t $DOCKER_IMAGE_NAME .

after_success:
- ./travis_docker_tag.sh
