sudo: required
language: go
go:
- 1.7.x
addons:
  apt:
    packages:
    - git
    - make
    - curl

env:
  global:
    - DOCKER_IMAGE_NAME=cloudposse/route53-kubernetes
    - RUN_TESTS=1

services:
- docker

install:
- make init
- make docker:login

script:
- make docker:build ARGS="RUN_TESTS"

after_success:
- make docker:build
- make travis:docker-tag-and-push
